### ISSUE TITLE
MQTT is getting unresponsive when Alarm is triggered

### ISSUE THREAD

**Issue by pilievwm** [alfredopironti/Paradox_IP150#6]
Hi, 

I love this project but there is a major issue with it. When there is triggered Alarm state, there is no information about it via MQTT. paradox/alarm/state reports about 'pending' but never 'triggered'.
My system is Spectra 65 (SP65)

The major issue is when the system is released from the Alarm state, the MQTT stop working for 24 hours. I notice that when I clear all MEMOs from the keyboard of the panel the MQTT start working again. I think there is an inconsistency with the communication after Alarm state.

Please advise how I can fix that.

**Comment by nikosbiss** [comment]
I have exactly the same issue!!

**Comment by alfredopironti** [comment]
Hi all, this should be fixed now in the latest revision of the add-on. There was an issue on how the information given on the Paradox web page was handled internally by the add-on, which made it crash. Thanks for bringing this forward.
