### ISSUE TITLE
Latest version of hass.io requires arch: option and install in addons/local directory

### ISSUE THREAD

**Issue by scstraus** [alfredopironti/Paradox_IP150#7]
Hi, I tried to install under hass.io supervisor 152, hass 90.2 and was not successful according to instructions provided:

```
cd /addons
git clone https://github.com/alfredopironti/Paradox_IP150.git paradox_ip150_mqtt
```

It simply didn't acknowledge the addon being there.

I had to change to 

```
cd /addons/local
git clone https://github.com/alfredopironti/Paradox_IP150.git paradox_ip150_mqtt
```
Then I got the following message in the supervisor log

```
19-04-03 21:55:56 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/local/paradox_ip150_mqtt/config.json: required key not provided @ data['arch']. Got None
```
So I had to add the arch option to config.json like so and then it showed up as an addon after another refresh..
```
{
  "name": "Paradox IP150 MQTT Adapter",
  "version": "0.5",
  "slug": "paradox_ip150_mqtt",
  "description": "Expose an MQTT interface for the Paradox IP150 web interface",
  "arch": ["amd64"],
  "url": "https://github.com/alfredopironti/Paradox_IP150",
  "startup": "services",
  "boot": "auto",
```

Would be good to update the instructions and config.json. I guess I will open a pull request against config.json.

**Comment by alfredopironti** [comment]
Hi, I think this is fixed now as I've added the arch parameter to the config.json, and bumped the version number so that user can update. Tested on HA 0.91.4 and HassOS 1.12.

Thanks for reporting this!
